import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import api, { apiError } from "@/lib/api";
import { useMasters } from "@/hooks/useMasters";
import { useAuth } from "@/context/AuthContext";
import { DocList } from "@/components/DocList";
import { DocMetaTabs } from "@/components/DocMetaTabs";
import { DocumentHeaderDefaults } from "@/components/DocumentHeaderDefaults";
import { DocumentMessageEditor, saveDocumentMessage } from "@/components/DocumentMessageEditor";
import { TransactionMutationActions } from "@/components/TransactionMutationActions";
import { PageHeader } from "@/components/PageHeader";
import { DatePicker, Field } from "@/components/DatePicker";
import { Combobox } from "@/components/Combobox";
import { StatusBadge } from "@/components/StatusBadge";
import { PullDialog } from "@/components/PullDialog";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { num, fmtDate, todayISO } from "@/lib/format";
import { inheritSourceHeader } from "@/lib/sourceInheritance";
import { Save, Printer, ArrowLeft, Download, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import { printDoc } from "@/lib/print";

export function DoList(){const[rows,setRows]=useState([]);useEffect(()=>{api.get("/do").then(r=>setRows(r.data));},[]);return <DocList title="DO — Penerimaan Barang" subtitle="Penerimaan fisik barang dari supplier" createPath="/do/new" basePath="/do" testidPrefix="do" rows={rows} columns={[{key:"no",label:"No. DO",mono:true},{key:"date",label:"Tanggal",render:r=>fmtDate(r.date)},{key:"supplier_name",label:"Supplier"},{key:"supplier_invoice",label:"No. Faktur"},{key:"line_count",label:"Item",num:true},{key:"status",label:"Status",status:true}]}/>;}

export function DoForm(){
  const{id}=useParams();const nav=useNavigate();const{can}=useAuth();const masters=useMasters();
  const[h,setH]=useState({date:todayISO(),supplier_id:"",supplier_dn:"",supplier_invoice:"",invoice_date:null,default_warehouse_id:"",default_project_id:"",default_unit_id:"",spk:"",receiver:"",notes:"",document_message:null});
  const[lines,setLines]=useState([]);const[doc,setDoc]=useState(null);const[pull,setPull]=useState(false);const[editing,setEditing]=useState(false);const isNew=!id;const editable=isNew||editing;
  const items=masters.map("items"),uoms=masters.map("uoms"); const uomLabel=uid=>{const u=uoms[uid];return u?(u.symbol||u.name||u.code):"";};
  const uomOptions=itemId=>{const it=items[itemId];if(!it?.base_uom_id)return[];return[{uom_id:it.base_uom_id,factor:1,is_base:true},...(it.uoms||[]).filter(x=>x.uom_id!==it.base_uom_id)].map(r=>{const u=uoms[r.uom_id]||{},short=u.symbol||u.name||u.code||"Satuan";return{value:r.uom_id,factor:Number(r.factor)||1,label:`${u.name||u.code||"Satuan"}${u.symbol?` (${u.symbol})`:""}${r.is_base?" — Dasar":` — 1 = ${num(r.factor)} ${uomLabel(it.base_uom_id)}`}`,selectedLabel:short,unit:short};});};
  const whOpts=(masters.data.warehouses||[]).map(d=>({value:d.id,label:`${d.code?d.code+" — ":""}${d.name}${d.location?` · ${d.location}`:""}`,selectedLabel:d.name}));
  const projOpts=(masters.data.projects||[]).map(d=>({value:d.id,label:`${d.code?d.code+" — ":""}${d.name}${d.pic?` · PIC ${d.pic}`:""}`,selectedLabel:d.name}));
  const unitOpts=(masters.data.units||[]).map(d=>({value:d.id,label:`${d.code?d.code+" — ":""}${d.name}${d.plate_no?` (${d.plate_no})`:""}${d.asset_no?` · Asset ${d.asset_no}`:""}`,selectedLabel:d.plate_no||d.name}));
  const load=()=>api.get(`/do/${id}`).then(r=>{setDoc(r.data);setH(r.data);setLines(r.data.lines.map(l=>({...l,_readonly:true})));setEditing(false);});
  useEffect(()=>{if(id)load();},[id]);
  const beginEdit=()=>{setEditing(true);setLines(cur=>cur.map(l=>({...l,_readonly:false,sources:l.po_line_id?[{po_id:l.po_id,line_id:l.po_line_id,qty:l.qty,base_qty:l.qty}]:[]})));};
  const setHeader=(next)=>{const n=typeof next==="function"?next(h):next;const changed=["default_project_id","default_unit_id"].filter(k=>(n[k]||"")!==(h[k]||""));if(changed.length)setLines(cur=>cur.map(l=>{const x={...l};changed.forEach(k=>{const field=k==="default_project_id"?"project_id":"unit_id",flag=k==="default_project_id"?"_projectOverride":"_unitOverride";if(!x[flag]&&(!x[field]||x[field]===h[k]))x[field]=n[k]||"";});return x;}));setH(n);};
  const changeWarehouse=v=>{const old=h.default_warehouse_id;setH({...h,default_warehouse_id:v});setLines(cur=>cur.map(l=>(!l._warehouseOverride&&(!l.warehouse_id||l.warehouse_id===old)?{...l,warehouse_id:v}:l)));};
  const onPull=picked=>{const add=picked.map(p=>({po_id:p.po_id,po_line_id:p.line_id,po_no:p.po_no,item_id:p.item_id,item_code:p.item_code,item_name:p.item_name,unit:p.unit,uom_id:p.uom_id,conversion_factor:p.conversion_factor||1,qty_po:p.qty_po,received_before:p.received,outstanding:p.outstanding,qty:p._qty,warehouse_id:p.warehouse_id||h.default_warehouse_id,project_id:p.project_id||h.default_project_id,unit_id:p.unit_id||h.default_unit_id,_warehouseOverride:!!p.warehouse_id,_projectOverride:!!p.project_id,_unitOverride:!!p.unit_id,_sourceHeader:p.source_header||null,condition:"Baik",notes:"",sources:[{po_id:p.po_id,line_id:p.line_id,qty:p._qty,base_qty:p._qty*(p.conversion_factor||1)}]}));const combined=[...lines,...add];setLines(combined);setH(cur=>inheritSourceHeader(cur,combined));};
  const upd=(i,patch)=>setLines(cur=>cur.map((l,x)=>{if(x!==i)return l;if(patch.uom_id!==undefined){const s=uomOptions(l.item_id).find(o=>o.value===patch.uom_id),oldF=Number(l.conversion_factor)||1,newF=Number(s?.factor)||1,base=(Number(l.qty)||0)*oldF;return{...l,uom_id:patch.uom_id,conversion_factor:newF,unit:s?.unit||l.unit,qty:base/newF};}const n={...l,...patch};if(patch.warehouse_id!==undefined)n._warehouseOverride=true;if(patch.project_id!==undefined)n._projectOverride=true;if(patch.unit_id!==undefined)n._unitOverride=true;if(patch.qty!==undefined&&n.sources?.length===1)n.sources=[{...n.sources[0],qty:Number(patch.qty)||0,base_qty:(Number(patch.qty)||0)*(Number(n.conversion_factor)||1)}];return n;}));
  const save=async()=>{try{if(isNew){const res=await api.post("/do",{...h,lines});await saveDocumentMessage("do",res.data.id,h.document_message);toast.success("DO diposting, stok bertambah dalam satuan dasar");nav(`/do/${res.data.id}`);}else{await api.put(`/transactions/do/${id}`,{...h,lines});await saveDocumentMessage("do",id,h.document_message);toast.success("DO diperbarui. Stok lama direversal lalu penerimaan diposting ulang.");load();}}catch(e){toast.error(apiError(e.response?.data?.detail));}};const ownQty=l=>num(l.display_qty??((Number(l.qty)||0)/(Number(l.conversion_factor)||1))),unitText=l=>l.display_unit||l.unit||"";
  return <div><PageHeader title={isNew?"DO Baru":doc?.no} subtitle={doc&&<StatusBadge status={doc.status}/>}><Button variant="outline" onClick={()=>nav("/do")}><ArrowLeft className="h-4 w-4 mr-2"/>Kembali</Button>{editable&&<Button variant="outline" onClick={()=>setPull(true)}><Download className="h-4 w-4 mr-2"/>Tarik PO</Button>}{!isNew&&!editing&&<TransactionMutationActions module="do" id={id} onEdit={beginEdit} onDeleted={()=>nav("/do")}/>} {editing&&<Button variant="outline" onClick={load}><X className="h-4 w-4 mr-2"/>Batal Edit</Button>}{editable&&can(isNew?"create":"edit")&&<Button onClick={save} disabled={lines.length===0}><Save className="h-4 w-4 mr-2"/>{editing?"Simpan Perubahan":"Posting Penerimaan"}</Button>}{!isNew&&!editing&&<Button variant="outline" onClick={()=>printDoc("DO",doc,{title:"PENERIMAAN BARANG"})}><Printer className="h-4 w-4 mr-2"/>Print</Button>}</PageHeader>
    <PullDialog open={pull} onClose={()=>setPull(false)} url={`/pull/po-for-do${h.supplier_id?"?supplier_id="+h.supplier_id:""}`} title="Tarik PO — Pilih Item Diterima" onConfirm={onPull} columns={[{key:"po_no",label:"PO",mono:true},{key:"supplier_name",label:"Supplier"},{key:"item_code",label:"Kode",mono:true},{key:"item_name",label:"Barang"},{key:"unit",label:"Satuan"},{key:"qty_po",label:"Qty PO",num:true},{key:"received",label:"Diterima",num:true},{key:"outstanding",label:"Sisa",num:true}]}/>
    <DocMetaTabs entity="do" entityId={id}><div className="space-y-4"><Card><CardContent className="pt-6 space-y-6"><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4"><Field label="Tanggal Penerimaan"><DatePicker value={h.date} onChange={v=>setH({...h,date:v})} disabled={!editable}/></Field><Field label="Supplier"><Combobox options={masters.opts("suppliers",d=>d.name)} value={h.supplier_id} onChange={v=>setH({...h,supplier_id:v})} disabled={!editable}/></Field><Field label="No. Surat Jalan"><Input value={h.supplier_dn||""} onChange={e=>setH({...h,supplier_dn:e.target.value})} disabled={!editable}/></Field><Field label="No. Faktur (opsional)"><Input value={h.supplier_invoice||""} onChange={e=>setH({...h,supplier_invoice:e.target.value})} disabled={!editable}/></Field><Field label="Gudang Default"><Combobox options={whOpts} value={h.default_warehouse_id} onChange={changeWarehouse} disabled={!editable}/></Field><DocumentHeaderDefaults h={h} setH={setHeader} masters={masters} readOnly={!editable}/><Field label="Petugas Penerima"><Input value={h.receiver||""} onChange={e=>setH({...h,receiver:e.target.value})} disabled={!editable}/></Field><Field label="Catatan"><Input value={h.notes||""} onChange={e=>setH({...h,notes:e.target.value})} disabled={!editable}/></Field></div>
      <div className="border rounded-md overflow-x-auto bg-card"><table className="w-full text-sm zebra min-w-[1280px]"><thead className="bg-muted"><tr className="text-left text-xs uppercase tracking-wider text-muted-foreground"><th className="p-2">PO</th><th className="p-2">Barang</th><th className="p-2 text-right">Qty PO</th><th className="p-2 text-right">Sebelumnya</th><th className="p-2 text-right">Sisa</th><th className="p-2 w-24">Qty Terima</th><th className="p-2 min-w-[145px]">Satuan</th><th className="p-2 min-w-[140px]">Gudang</th><th className="p-2 min-w-[140px]">Proyek</th><th className="p-2 min-w-[140px]">Unit/Aset</th><th className="p-2 w-24">Kondisi</th>{editable&&<th className="p-2 w-10"/>}</tr></thead><tbody>{lines.length===0&&<tr><td colSpan={12} className="p-6 text-center text-muted-foreground">Tarik PO untuk menambah item</td></tr>}{lines.map((l,i)=><tr key={i} className="border-t align-top"><td className="p-2 font-mono text-xs">{l.po_no}</td><td className="p-2">{l.item_name||l.item_code}</td><td className="p-2 text-right">{num(l.qty_po)}</td><td className="p-2 text-right">{num(l.received_before)}</td><td className="p-2 text-right">{num(l.outstanding)}</td><td className="p-1.5">{editable?<Input type="number" step="any" value={l.qty} onChange={e=>upd(i,{qty:e.target.value})} className="h-9 text-right"/>:ownQty(l)}</td><td className="p-1.5">{editable?<div><Combobox options={uomOptions(l.item_id)} value={l.uom_id||items[l.item_id]?.base_uom_id||""} onChange={v=>upd(i,{uom_id:v})}/><div className="mt-1 text-[10px] text-muted-foreground">Stok: {num((Number(l.qty)||0)*(Number(l.conversion_factor)||1))} {uomLabel(items[l.item_id]?.base_uom_id)}</div></div>:unitText(l)}</td><td className="p-1.5">{editable?<Combobox options={whOpts} value={l.warehouse_id||""} onChange={v=>upd(i,{warehouse_id:v})}/>:l.warehouse_name}</td><td className="p-1.5">{editable?<Combobox options={projOpts} value={l.project_id||""} onChange={v=>upd(i,{project_id:v})}/>:l.project_name||"-"}</td><td className="p-1.5">{editable?<Combobox options={unitOpts} value={l.unit_id||""} onChange={v=>upd(i,{unit_id:v})}/>:l.unit_name||"-"}</td><td className="p-1.5">{editable?<Input value={l.condition} onChange={e=>upd(i,{condition:e.target.value})} className="h-9"/>:l.condition}</td>{editable&&<td className="p-1.5"><Button variant="ghost" size="icon" className="h-9 w-9" onClick={()=>setLines(lines.filter((_,x)=>x!==i))}><Trash2 className="h-4 w-4 text-destructive"/></Button></td>}</tr>)}</tbody></table></div>
    </CardContent></Card><DocumentMessageEditor module="do" value={h.document_message} onChange={v=>setH({...h,document_message:v})} useDefault={isNew} readOnly={!editable}/></div></DocMetaTabs>
  </div>;
}
