import { useEffect, useState } from "react";
import api, { apiError } from "@/lib/api";
import { useMasters } from "@/hooks/useMasters";
import { useAuth } from "@/context/AuthContext";
import { PageHeader } from "@/components/PageHeader";
import { ItemLines } from "@/components/ItemLines";
import { DocumentMessageEditor, saveDocumentMessage } from "@/components/DocumentMessageEditor";
import { TransactionMutationActions } from "@/components/TransactionMutationActions";
import { LoanReturnActions } from "@/components/LoanReturnActions";
import { DatePicker, Field } from "@/components/DatePicker";
import { Combobox } from "@/components/Combobox";
import { StatusBadge } from "@/components/StatusBadge";
import { PullDialog } from "@/components/PullDialog";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Plus, ArrowLeft, Undo2, X, Save } from "lucide-react";
import { num, fmtDate, todayISO } from "@/lib/format";
import { toast } from "sonner";

const EMPTY = () => ({ date: todayISO(), from_warehouse_id: "", to_warehouse_id: "", due_date: null, project_id: "", requester: "", notes: "", document_message: null });

export default function Loan() {
  const masters = useMasters(); const { can } = useAuth();
  const [rows, setRows] = useState([]); const [mode, setMode] = useState("list");
  const [h, setH] = useState(EMPTY());
  const [lines, setLines] = useState([]); const [detail, setDetail] = useState(null); const [ret, setRet] = useState(false); const [editingId,setEditingId]=useState(null);
  const [returns,setReturns]=useState([]); const [returnEdit,setReturnEdit]=useState(null); const [returnLines,setReturnLines]=useState([]);
  const load = () => api.get("/loans").then((r) => setRows(r.data));
  useEffect(() => { load(); }, []);

  const startNew=()=>{setEditingId(null);setH(EMPTY());setLines([]);setDetail(null);setReturns([]);setMode("form");};
  const startEdit=()=>{if(!detail)return;setEditingId(detail.id);setH({date:detail.date,from_warehouse_id:detail.from_warehouse_id||"",to_warehouse_id:detail.to_warehouse_id||"",due_date:detail.due_date||null,project_id:detail.project_id||"",requester:detail.requester||"",notes:detail.notes||"",document_message:detail.document_message||""});setLines((detail.lines||[]).map(l=>({...l,_readonly:false})));setMode("form");};
  const save = async () => { try { const res=editingId?await api.put(`/transactions/loan/${editingId}`,{...h,lines}):await api.post("/loans", { ...h, lines }); const keep=editingId||res.data.id; await saveDocumentMessage("loan",keep,h.document_message); toast.success(editingId?"Pinjaman diperbarui; stok direversal lalu diposting ulang":`Pinjaman ${res.data.no} dibuat`);setMode("list");setLines([]);setH(EMPTY());setEditingId(null);load();if(keep)openDetail(keep);} catch (e) { toast.error(apiError(e.response?.data?.detail)); } };
  const openDetail = async (id) => { try { const [a,b]=await Promise.all([api.get(`/loans/${id}`),api.get(`/loans/${id}/returns`)]); setDetail(a.data); setReturns(b.data||[]); setRet(false); setReturnEdit(null); } catch(e){toast.error(apiError(e.response?.data?.detail));} };
  const onReturn = async (picked) => { try { await api.post(`/loans/${detail.id}/return`, { lines: picked.map((p) => ({ loan_line_id: p.loan_line_id, qty: p._qty })) }); toast.success("Pengembalian diposting"); openDetail(detail.id); load(); } catch (e) { toast.error(apiError(e.response?.data?.detail)); } };
  const beginReturnEdit=(row)=>{setReturnEdit({...row,date:row.date||todayISO(),notes:row.notes||""});setReturnLines((row.lines||[]).map(l=>({...l,qty:Number(l.qty)||0})));};
  const saveReturnEdit=async()=>{try{await api.put(`/loan-returns/${returnEdit.id}`,{date:returnEdit.date,notes:returnEdit.notes,lines:returnLines.map(l=>({loan_line_id:l.loan_line_id,qty:Number(l.qty)||0}))});toast.success("Return diperbarui; stok direversal lalu diposting ulang");setReturnEdit(null);openDetail(detail.id);load();}catch(e){toast.error(apiError(e.response?.data?.detail));}};
  const factor = (l) => Number(l.conversion_factor) || 1;
  const ownQty = (l) => num(l.display_qty ?? ((Number(l.qty) || 0) / factor(l)));
  const convQty = (l, v) => num((Number(v) || 0) / factor(l));
  const unitText = (l) => l.display_unit || l.unit || "";

  if (mode === "form") return <div><PageHeader title={editingId?"Edit Pinjaman":"Pinjaman Baru"} subtitle={editingId?"Perubahan akan melakukan reversal stok lama lalu posting ulang":"Pinjam barang antar gudang"}><Button variant="outline" onClick={() => {setMode("list");setEditingId(null);}}><ArrowLeft className="h-4 w-4 mr-2" />Kembali</Button><Button onClick={save} disabled={lines.length === 0}>{editingId?"Simpan Perubahan":"Posting Pinjaman"}</Button></PageHeader><div className="space-y-4"><Card><CardContent className="pt-6 space-y-6"><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4"><Field label="Tanggal"><DatePicker value={h.date} onChange={(v) => setH({ ...h, date: v })} /></Field><Field label="Gudang Pemberi"><Combobox options={masters.opts("warehouses")} value={h.from_warehouse_id} onChange={(v) => setH({ ...h, from_warehouse_id: v })} /></Field><Field label="Gudang Peminjam"><Combobox options={masters.opts("warehouses")} value={h.to_warehouse_id} onChange={(v) => setH({ ...h, to_warehouse_id: v })} /></Field><Field label="Target Pengembalian"><DatePicker value={h.due_date} onChange={(v) => setH({ ...h, due_date: v })} /></Field><Field label="Pemohon"><Input value={h.requester} onChange={(e) => setH({ ...h, requester: e.target.value })} /></Field><Field label="Keterangan"><Input value={h.notes} onChange={(e) => setH({ ...h, notes: e.target.value })} /></Field></div><ItemLines lines={lines} onChange={setLines} masters={masters} fields={{ project: true, unit: true, notes: true }} /></CardContent></Card><DocumentMessageEditor module="loan" value={h.document_message} onChange={(v)=>setH({...h,document_message:v})} useDefault={!editingId} /></div></div>;

  return <div>
    <PageHeader title="Pinjam Antar Gudang" subtitle="Pinjaman dengan kewajiban pengembalian">{can("create") && <Button onClick={startNew}><Plus className="h-4 w-4 mr-2" />Buat Pinjaman</Button>}</PageHeader>
    <div className="border rounded-md overflow-x-auto bg-card shadow-sm"><table className="w-full text-sm zebra"><thead className="bg-muted"><tr className="text-left text-xs uppercase tracking-wider text-muted-foreground"><th className="p-3">No. Pinjaman</th><th className="p-3">Tanggal</th><th className="p-3">Pemberi</th><th className="p-3">Peminjam</th><th className="p-3 text-right">Outstanding Dasar</th><th className="p-3">Status</th></tr></thead><tbody>{rows.length === 0 && <tr><td colSpan={6} className="p-8 text-center text-muted-foreground">Belum ada pinjaman</td></tr>}{rows.map((r) => <tr key={r.id} onClick={() => openDetail(r.id)} className={`border-t cursor-pointer hover:bg-accent/40 ${detail?.id === r.id ? "bg-primary/5" : ""}`}><td className="p-3 font-mono text-xs font-semibold">{r.no}</td><td className="p-3">{fmtDate(r.date)}</td><td className="p-3">{r.from_name}</td><td className="p-3">{r.to_name}</td><td className="p-3 text-right">{num(r.outstanding_total)}</td><td className="p-3"><StatusBadge status={r.status} /></td></tr>)}</tbody></table></div>
    {detail && <Card className="mt-4 border-primary/20"><CardContent className="pt-5 space-y-4"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-semibold uppercase tracking-wider text-primary">Detail Pinjaman</div><div className="mt-1 flex flex-wrap items-center gap-2"><span className="text-xs font-semibold text-muted-foreground">No. Pinjaman</span><h2 className="font-head font-mono text-lg font-semibold">{detail.no}</h2><StatusBadge status={detail.status} /></div><div className="mt-1 text-sm text-muted-foreground">{detail.from_name} → {detail.to_name} · Target kembali: {fmtDate(detail.due_date)}</div><div className="mt-2"><TransactionMutationActions module="loan" id={detail.id} onEdit={startEdit} onDeleted={()=>{setDetail(null);setReturns([]);load();}} compact /></div></div><Button variant="ghost" size="icon" onClick={() => { setDetail(null); setRet(false); }}><X className="h-4 w-4" /></Button></div>
      <div className="border rounded-md overflow-x-auto"><table className="w-full text-sm zebra"><thead className="bg-muted"><tr className="text-left text-xs uppercase text-muted-foreground"><th className="p-2">Barang</th><th className="p-2">Satuan</th><th className="p-2 text-right">Pinjam</th><th className="p-2 text-right">Kembali</th><th className="p-2 text-right">Outstanding</th></tr></thead><tbody>{detail.lines.map((l, i) => <tr key={i} className="border-t"><td className="p-2">{l.item_code} — {l.item_name}</td><td className="p-2">{unitText(l)}</td><td className="p-2 text-right">{ownQty(l)}</td><td className="p-2 text-right">{convQty(l, l.returned)}</td><td className="p-2 text-right font-semibold">{convQty(l, l.outstanding)}</td></tr>)}</tbody></table></div>
      <DocumentMessageEditor module="loan" value={detail.document_message||""} readOnly />
      {detail.outstanding_total > 0 && can("create") && <Button onClick={() => setRet(!ret)}><Undo2 className="h-4 w-4 mr-2" />{ret ? "Tutup Form Return" : "Return Pinjaman"}</Button>}
      <PullDialog open={ret} onClose={() => setRet(false)} url={`/loans/${detail.id}/returnable`} title="Return Pinjaman" idKey="loan_line_id" onConfirm={onReturn} columns={[{ key: "item_code", label: "Kode", mono: true }, { key: "item_name", label: "Barang" }, { key: "unit", label: "Satuan" }, { key: "qty", label: "Pinjam", num: true }, { key: "returned", label: "Kembali", num: true }, { key: "outstanding", label: "Outstanding", num: true }]} />
      <div className="border-t pt-4"><div className="font-head font-semibold mb-2">Riwayat Return</div>{returns.length===0?<div className="text-sm text-muted-foreground">Belum ada return.</div>:<div className="space-y-2">{returns.map(r=><div key={r.id} className="rounded-lg border p-3"><div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between"><div><div className="font-mono text-xs font-semibold">{r.no}</div><div className="text-xs text-muted-foreground">{fmtDate(r.date)} · {(r.lines||[]).map(l=>`${l.item_code||l.item_name}: ${num(l.qty)}`).join(", ")||"Detail legacy"}</div></div><LoanReturnActions row={r} onEdit={beginReturnEdit} onDeleted={()=>{openDetail(detail.id);load();}} /></div>{r.legacy_ambiguous&&<div className="mt-2 text-xs text-destructive">Return lama ini tidak memiliki jejak baris unik, sehingga edit/hapus otomatis dikunci untuk menjaga stok.</div>}</div>)}</div>}</div>
      {returnEdit&&<div className="rounded-xl border border-primary/20 p-4 space-y-3"><div className="flex items-center justify-between"><div><div className="text-xs uppercase font-semibold text-primary">Edit Return</div><div className="font-mono text-sm font-semibold">{returnEdit.no}</div></div><Button variant="ghost" size="icon" onClick={()=>setReturnEdit(null)}><X className="h-4 w-4"/></Button></div><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><Field label="Tanggal"><DatePicker value={returnEdit.date} onChange={v=>setReturnEdit({...returnEdit,date:v})}/></Field><Field label="Catatan"><Input value={returnEdit.notes||""} onChange={e=>setReturnEdit({...returnEdit,notes:e.target.value})}/></Field></div><div className="space-y-2">{returnLines.map((l,i)=><div key={l.id||i} className="grid grid-cols-[1fr_140px] gap-3 items-center"><div className="text-sm">{l.item_code} — {l.item_name}</div><Input type="number" step="any" value={l.qty} onChange={e=>setReturnLines(cur=>cur.map((x,j)=>j===i?{...x,qty:e.target.value}:x))} className="text-right"/></div>)}</div><Button onClick={saveReturnEdit}><Save className="h-4 w-4 mr-2"/>Simpan Perubahan Return</Button></div>}
    </CardContent></Card>}
  </div>;
}