import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import api, { apiError } from "@/lib/api";
import { useMasters } from "@/hooks/useMasters";
import { useAuth } from "@/context/AuthContext";
import { ItemLines } from "@/components/ItemLines";
import { DocMetaTabs } from "@/components/DocMetaTabs";
import { DocumentHeaderDefaults } from "@/components/DocumentHeaderDefaults";
import { DocumentMessageEditor, saveDocumentMessage } from "@/components/DocumentMessageEditor";
import { TransactionMutationActions } from "@/components/TransactionMutationActions";
import { PageHeader } from "@/components/PageHeader";
import { TransactionProgress } from "@/components/TransactionProgress";
import { DatePicker, Field } from "@/components/DatePicker";
import { Combobox } from "@/components/Combobox";
import { StatusBadge } from "@/components/StatusBadge";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { num, fmtDate, todayISO } from "@/lib/format";
import { Save, Send, Printer, Ban, ArrowLeft, Search, Plus, X } from "lucide-react";
import { toast } from "sonner";
import { printDoc } from "@/lib/print";

const FLOW = ["MRO", "RO", "PO", "DO", "MI"];
function lifecycleStage(t) {
  const req = Number(t?.request || 0), ro = Number(t?.qty_ro || 0), po = Number(t?.qty_po || 0), received = Number(t?.qty_received || 0), mi = Number(t?.qty_mi || 0);
  if (req > 0 && mi >= req) return "Completed"; if (mi > 0) return "MI"; if (received > 0) return "DO"; if (po > 0) return "PO"; if (ro > 0) return "RO"; return "MRO";
}
function FlowMini({ stage }) {
  const current = stage === "Completed" ? 4 : Math.max(0, FLOW.indexOf(stage));
  return <div className="flex min-w-[280px] items-center gap-1.5">{FLOW.map((x, i) => { const done = stage === "Completed" || i < current, active = stage !== "Completed" && i === current; return <div key={x} className="flex items-center gap-1.5"><div className={`flex h-7 min-w-9 items-center justify-center rounded-full px-2 text-[10px] font-semibold ${done ? "bg-emerald-100 text-emerald-700" : active ? "bg-blue-100 text-blue-700 ring-1 ring-blue-200" : "bg-muted text-muted-foreground"}`}>{x}</div>{i < FLOW.length - 1 && <div className={`h-px w-3 ${done ? "bg-emerald-300" : "bg-border"}`} />}</div>; })}</div>;
}

export function MroList() {
  const nav = useNavigate(); const [rows, setRows] = useState([]); const [trace, setTrace] = useState([]); const [q, setQ] = useState(""); const [stageFilter, setStageFilter] = useState("all");
  useEffect(() => { Promise.all([api.get("/mro"), api.get("/reports/mro-traceability")]).then(([a, b]) => { setRows(a.data || []); setTrace(b.data || []); }); }, []);
  const traceByMro = useMemo(() => { const map = {}; for (const t of trace) { const k = t.mro_id; if (!k) continue; if (!map[k]) map[k] = { request: 0, qty_ro: 0, qty_po: 0, qty_received: 0, qty_mi: 0, outstanding: 0 }; ["request","qty_ro","qty_po","qty_received","qty_mi","outstanding"].forEach((x) => map[k][x] += Number(t[x] || 0)); } return map; }, [trace]);
  const enriched = useMemo(() => rows.map((r) => { const t = traceByMro[r.id] || { request: 0, qty_ro: 0, qty_po: 0, qty_received: 0, qty_mi: 0, outstanding: r.outstanding_total || 0 }; return { ...r, lifecycle: t, lifecycle_stage: lifecycleStage(t) }; }), [rows, traceByMro]);
  const counts = useMemo(() => { const out = { all: enriched.length, MRO: 0, RO: 0, PO: 0, DO: 0, MI: 0, Completed: 0 }; enriched.forEach((r) => out[r.lifecycle_stage]++); return out; }, [enriched]);
  const cards = [{ key:"all",label:"Total MRO",desc:"Seluruh transaksi"},{key:"MRO",label:"Belum ke RO",desc:"Masih di tahap MRO"},{key:"RO",label:"Sampai RO",desc:"Belum menjadi PO"},{key:"PO",label:"Sampai PO",desc:"Belum ada penerimaan"},{key:"DO",label:"Sampai DO",desc:"Barang sudah diterima"},{key:"MI",label:"Sampai MI",desc:"Pengeluaran masih partial"},{key:"Completed",label:"Selesai",desc:"MI memenuhi request"}];
  const filtered = enriched.filter((r) => (!q || `${r.no || ""} ${r.requester || ""} ${r.division_name || ""}`.toLowerCase().includes(q.toLowerCase())) && (stageFilter === "all" || r.lifecycle_stage === stageFilter));
  return <div><PageHeader title="MRO — Material Request Order" subtitle="Pengajuan kebutuhan material dan monitoring lifecycle transaksi"><Button onClick={() => nav("/mro/new")}><Plus className="h-4 w-4 mr-2" />Buat Baru</Button></PageHeader>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-7 mb-5">{cards.map((c) => <button key={c.key} onClick={() => setStageFilter(c.key)} className={`rounded-xl border bg-card p-4 text-left shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-md ${stageFilter === c.key ? "border-primary ring-1 ring-primary/20" : ""}`}><div className="text-2xl font-bold tabular-nums">{counts[c.key] || 0}</div><div className="mt-1 text-sm font-semibold">{c.label}</div><div className="mt-0.5 text-[11px] text-muted-foreground">{c.desc}</div></button>)}</div>
    <div className="mb-4 flex gap-3"><div className="relative max-w-sm flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={q} onChange={(e)=>setQ(e.target.value)} placeholder="Cari MRO, pemohon, divisi..." className="pl-9"/></div>{stageFilter !== "all" && <Button variant="outline" onClick={()=>setStageFilter("all")}>Tampilkan Semua</Button>}</div>
    <div className="overflow-x-auto rounded-xl border bg-card shadow-sm"><table className="w-full min-w-[1250px] text-sm zebra"><thead className="bg-muted"><tr className="text-left text-xs uppercase tracking-wider text-muted-foreground"><th className="p-3">No. MRO</th><th className="p-3">Tanggal</th><th className="p-3">Pemohon</th><th className="p-3">Divisi</th><th className="p-3 text-right">Item</th><th className="p-3">Tracking</th><th className="p-3 text-right">Request</th><th className="p-3 text-right">MI</th><th className="p-3 text-right">Outstanding</th><th className="p-3">Status</th></tr></thead><tbody>{filtered.length===0&&<tr><td colSpan={10} className="p-8 text-center text-muted-foreground">Belum ada transaksi pada filter ini</td></tr>}{filtered.map((r)=><tr key={r.id} onClick={()=>nav(`/mro/${r.id}`)} className="border-t cursor-pointer hover:bg-accent/40"><td className="p-3 font-mono text-xs font-semibold text-primary">{r.no}</td><td className="p-3">{fmtDate(r.date)}</td><td className="p-3">{r.requester||"-"}</td><td className="p-3">{r.division_name||"-"}</td><td className="p-3 text-right">{num(r.line_count)}</td><td className="p-3"><FlowMini stage={r.lifecycle_stage}/></td><td className="p-3 text-right">{num(r.lifecycle.request)}</td><td className="p-3 text-right">{num(r.lifecycle.qty_mi)}</td><td className="p-3 text-right font-semibold">{num(r.lifecycle.outstanding)}</td><td className="p-3"><StatusBadge status={r.status}/></td></tr>)}</tbody></table></div>
  </div>;
}

export function MroForm() {
  const { id } = useParams(); const nav = useNavigate(); const { can } = useAuth(); const masters = useMasters();
  const [h, setH] = useState({ date: todayISO(), requester: "", department: "", division_id: "", default_warehouse_id: "", default_project_id: "", default_unit_id: "", spk: "", need_date: null, notes: "", document_message: null });
  const [lines, setLines] = useState([]); const [doc, setDoc] = useState(null); const [editing,setEditing]=useState(false); const isNew = !id;
  const load = () => api.get(`/mro/${id}`).then((r) => { setDoc(r.data); setH(r.data); setLines(r.data.lines.map((l) => ({ ...l }))); setEditing(false); });
  useEffect(() => { if (id) load(); }, [id]); const submitted = doc?.submitted; const waitingApproval = doc?.approval_status === "Waiting Approval"; const readOnly = !isNew && !editing && (submitted || waitingApproval);
  const save = async (submit=false) => { try { const payload={...h,submitted:false,lines}; let res; if(isNew) res=await api.post("/mro",payload); else { await api.put(`/transactions/mro/${id}`,payload); res={data:{id}}; } await saveDocumentMessage("mro",res.data.id,h.document_message); if(submit) await api.post(`/mro/${res.data.id}/submit`); toast.success(submit?"MRO disubmit":"MRO tersimpan"); nav(`/mro/${res.data.id}`); if(!isNew) load(); } catch(e){toast.error(apiError(e.response?.data?.detail));} };
  const doSubmit=async()=>{try{await api.post(`/mro/${id}/submit`);toast.success("MRO disubmit");load();}catch(e){toast.error(apiError(e.response?.data?.detail));}}; const doCancel=async()=>{await api.post(`/mro/${id}/cancel`,{reason:"Dibatalkan user"});toast.success("MRO dibatalkan");load();};
  const factor=(l)=>Number(l.conversion_factor)||1, q=(l,v)=>num((Number(v)||0)/factor(l)), unitText=(l)=>l.display_unit||l.unit||"";
  const defaults={warehouse_id:h.default_warehouse_id,project_id:h.default_project_id,unit_id:h.default_unit_id};
  return <div><PageHeader title={isNew?"MRO Baru":doc?.no} subtitle={doc&&<StatusBadge status={doc.status}/>}><Button variant="outline" onClick={()=>nav("/mro")}><ArrowLeft className="h-4 w-4 mr-2"/>Kembali</Button>{!isNew&&!editing&&<TransactionMutationActions module="mro" id={id} onEdit={()=>setEditing(true)} onDeleted={()=>nav("/mro")}/>} {editing&&<Button variant="outline" onClick={load}><X className="h-4 w-4 mr-2"/>Batal Edit</Button>}{(!readOnly||editing)&&can("edit")&&!isNew&&<Button variant="outline" onClick={()=>save(false)}><Save className="h-4 w-4 mr-2"/>Simpan Perubahan</Button>}{isNew&&can("create")&&<Button variant="outline" onClick={()=>save(false)}><Save className="h-4 w-4 mr-2"/>Simpan Draft</Button>}{isNew&&can("submit")&&<Button onClick={()=>save(true)}><Send className="h-4 w-4 mr-2"/>Simpan & Submit</Button>}{!isNew&&!submitted&&!waitingApproval&&!editing&&can("submit")&&<Button onClick={doSubmit}><Send className="h-4 w-4 mr-2"/>Submit</Button>}{!isNew&&doc&&!doc.cancelled&&!editing&&can("cancel")&&<Button variant="outline" onClick={doCancel}><Ban className="h-4 w-4 mr-2"/>Batalkan</Button>}{!isNew&&!editing&&<Button variant="outline" onClick={()=>printDoc("MRO",doc)}><Printer className="h-4 w-4 mr-2"/>Print</Button>}</PageHeader>
    <TransactionProgress className="mb-4" stages={["Draft","Waiting Approval","Open","Partial","Completed"]} status={isNew?"Draft":editing?"Edit":doc?.status}/><DocMetaTabs entity="mro" entityId={id}><div className="space-y-4"><Card><CardContent className="pt-6 space-y-6"><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4"><Field label="Tanggal MRO"><DatePicker value={h.date} onChange={(v)=>setH({...h,date:v})}/></Field><Field label="Tanggal Kebutuhan"><DatePicker value={h.need_date} onChange={(v)=>setH({...h,need_date:v})}/></Field><Field label="Divisi"><Combobox options={masters.opts("divisions",d=>d.name)} value={h.division_id} onChange={(v)=>setH({...h,division_id:v})}/></Field><Field label="Pemohon"><Input value={h.requester||""} onChange={(e)=>setH({...h,requester:e.target.value})} disabled={readOnly}/></Field><Field label="Departemen"><Input value={h.department||""} onChange={(e)=>setH({...h,department:e.target.value})} disabled={readOnly}/></Field><Field label="Gudang Default"><Combobox options={masters.opts("warehouses",d=>d.name)} value={h.default_warehouse_id} onChange={(v)=>setH({...h,default_warehouse_id:v})} disabled={readOnly}/></Field><DocumentHeaderDefaults h={h} setH={setH} masters={masters} readOnly={readOnly}/><Field label="Keterangan"><Input value={h.notes||""} onChange={(e)=>setH({...h,notes:e.target.value})} disabled={readOnly}/></Field></div>
      {readOnly?<div className="border rounded-md overflow-x-auto"><table className="w-full text-sm zebra"><thead className="bg-muted"><tr className="text-left text-xs uppercase text-muted-foreground"><th className="p-2">Barang</th><th className="p-2">Satuan</th><th className="p-2 text-right">Request</th><th className="p-2 text-right">RO</th><th className="p-2 text-right">PO</th><th className="p-2 text-right">Diterima</th><th className="p-2 text-right">MI</th><th className="p-2 text-right">Outstanding</th></tr></thead><tbody>{lines.map((l,i)=><tr key={i} className="border-t"><td className="p-2">{l.item_code} — {l.item_name}</td><td className="p-2">{unitText(l)}</td><td className="p-2 text-right">{q(l,l.monitor?.qty_request)}</td><td className="p-2 text-right">{q(l,l.monitor?.qty_ro)}</td><td className="p-2 text-right">{q(l,l.monitor?.qty_po)}</td><td className="p-2 text-right">{q(l,l.monitor?.qty_received)}</td><td className="p-2 text-right">{q(l,l.monitor?.qty_mi)}</td><td className="p-2 text-right font-semibold">{q(l,l.monitor?.outstanding)}</td></tr>)}</tbody></table></div>:<ItemLines lines={lines} onChange={setLines} masters={masters} fields={{warehouse:true,project:true,unit:true,notes:true}} defaults={defaults}/>}</CardContent></Card><DocumentMessageEditor module="mro" value={h.document_message} onChange={(v)=>setH({...h,document_message:v})} useDefault={isNew} readOnly={!isNew&&!editing}/></div></DocMetaTabs>
  </div>;
}
