import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import api, { apiError } from "@/lib/api";
import { useMasters } from "@/hooks/useMasters";
import { useAuth } from "@/context/AuthContext";
import { DocList } from "@/components/DocList";
import { ItemLines } from "@/components/ItemLines";
import { DocMetaTabs } from "@/components/DocMetaTabs";
import { DocumentHeaderDefaults } from "@/components/DocumentHeaderDefaults";
import { DocumentMessageEditor, saveDocumentMessage } from "@/components/DocumentMessageEditor";
import { TransactionMutationActions } from "@/components/TransactionMutationActions";
import { PageHeader } from "@/components/PageHeader";
import { TransactionProgress } from "@/components/TransactionProgress";
import { DatePicker, Field } from "@/components/DatePicker";
import { Combobox } from "@/components/Combobox";
import { StatusBadge } from "@/components/StatusBadge";
import { PullDialog } from "@/components/PullDialog";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { num, rupiah, fmtDate, fmtDateTime, todayISO } from "@/lib/format";
import { inheritSourceHeader } from "@/lib/sourceInheritance";
import { Save, Send, Printer, Ban, ArrowLeft, Download, Check, X, Mail } from "lucide-react";
import { toast } from "sonner";
import { printDoc } from "@/lib/print";

export function PoList(){const[rows,setRows]=useState([]);useEffect(()=>{api.get("/po").then(r=>setRows(r.data));},[]);return <DocList title="PO — Purchase Order" subtitle="Pesanan pembelian ke supplier" createPath="/po/new" basePath="/po" testidPrefix="po" rows={rows} columns={[{key:"no",label:"No. PO",mono:true},{key:"date",label:"Tanggal",render:r=>fmtDate(r.date)},{key:"supplier_name",label:"Supplier"},{key:"buyer_contact_name",label:"Buyer"},{key:"grand_total",label:"Nilai",num:true,render:r=>r.grand_total==null?"***":rupiah(r.grand_total)},{key:"status",label:"Status",status:true}]}/>;}
function addDaysISO(base,days){if(!base||!Number(days))return null;const d=new Date(`${String(base).slice(0,10)}T00:00:00`);if(Number.isNaN(d.getTime()))return null;d.setDate(d.getDate()+Number(days));return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}

export function PoForm(){
  const{id}=useParams();const nav=useNavigate();const{can}=useAuth();const masters=useMasters();
  const[h,setH]=useState({date:todayISO(),supplier_id:"",supplier_ref:"",buyer_contact_id:"",division_id:"",payment_term:"",delivery_term:"",currency:"IDR",supplier_bank_id:"",default_tax_id:"",eta:null,default_warehouse_id:"",default_project_id:"",default_unit_id:"",spk:"",tax_inclusive:false,supplier_notes:"",internal_notes:"",document_message:null});
  const[lines,setLines]=useState([]);const[doc,setDoc]=useState(null);const[pull,setPull]=useState(false);const[editing,setEditing]=useState(false);const isNew=!id;const canPrice=can("view_purchase_price");
  const supplierMap=masters.map("suppliers"),taxesMap=masters.map("taxes"),divisionMap=masters.map("divisions"),selectedSupplier=supplierMap[h.supplier_id]||null;
  const bankOptions=(selectedSupplier?.banks||[]).map(b=>({value:b.id,label:`${b.bank_name||"Bank"} — ${b.account_no||"-"}${b.account_name?` · ${b.account_name}`:""}${b.is_primary?" · Utama":""}`,selectedLabel:`${b.bank_name||"Bank"} · ${b.account_no||"-"}`}));
  const buyerOptions=(masters.data.contacts||[]).map(c=>({value:c.id,label:`${c.name||"Tanpa Nama"}${c.position?` — ${c.position}`:""}${c.division_id&&divisionMap[c.division_id]?.name?` · ${divisionMap[c.division_id].name}`:""}`,selectedLabel:c.name||c.code}));
  const load=()=>api.get(`/po/${id}`).then(r=>{setDoc(r.data);setH(r.data);setLines(r.data.lines.map(l=>({...l,_taxInitialized:true,_readonly:true})));setEditing(false);});useEffect(()=>{if(id)load();},[id]);
  const beginEdit=()=>{setEditing(true);setLines(cur=>cur.map(l=>({...l,_readonly:false})));};
  const taxPatch=(taxId)=>{const t=taxId?taxesMap[taxId]:null;return{tax_id:taxId||"",tax:Number(t?.rate)||0,tax_name:t?.name||null,_taxInitialized:true};};
  const handleLinesChange=(next)=>setLines(next.map(l=>l._taxInitialized?l:({...l,...taxPatch(h.default_tax_id)})));
  const changeSupplier=(supplierId)=>{const s=supplierMap[supplierId]||{},bank=(s.banks||[]).find(b=>b.is_primary)||(s.banks||[])[0],taxId=s.default_tax_id||"";setH(prev=>({...prev,supplier_id:supplierId,payment_term:s.payment_term||"",delivery_term:s.delivery_term||s.delivery_days||"",currency:s.currency||"IDR",supplier_bank_id:bank?.id||"",default_tax_id:taxId,eta:s.lead_time_days?(addDaysISO(prev.date,s.lead_time_days)||prev.eta):prev.eta}));if(taxId)setLines(cur=>cur.map(l=>l.tax_id?l:({...l,...taxPatch(taxId)})));};
  const onPull=(picked)=>{const add=picked.map(p=>({item_id:p.item_id,qty:p._qty,unit:p.unit,uom_id:p.uom_id,conversion_factor:p.conversion_factor||1,warehouse_id:p.warehouse_id||h.default_warehouse_id,project_id:p.project_id||h.default_project_id,unit_id:p.unit_id||h.default_unit_id,_warehouseOverride:!!p.warehouse_id,_projectOverride:!!p.project_id,_unitOverride:!!p.unit_id,price:0,discount:0,_locked:true,_sourceHeader:p.source_header||null,...taxPatch(h.default_tax_id),_sourceLabel:`RO: ${p.ro_no}${p.mro_no?" / MRO: "+p.mro_no:""}`,sources:[{ro_id:p.ro_id,line_id:p.line_id,qty:p._qty,base_qty:p._qty*(p.conversion_factor||1)}]}));const combined=[...lines,...add];setLines(combined);setH(cur=>inheritSourceHeader(cur,combined));if(!h.supplier_id&&picked[0]?.supplier_id)changeSupplier(picked[0].supplier_id);};
  const save=async()=>{try{if(isNew){const res=await api.post("/po",{...h,lines});await saveDocumentMessage("po",res.data.id,h.document_message);toast.success("PO tersimpan");nav(`/po/${res.data.id}`);}else{await api.put(`/transactions/po/${id}`,{...h,lines});await saveDocumentMessage("po",id,h.document_message);toast.success("Perubahan PO tersimpan. Approval direset dan PO kembali Draft.");load();}}catch(e){toast.error(apiError(e.response?.data?.detail));}};
  const act=async(path,body)=>{try{await api.post(`/po/${id}/${path}`,body||{});toast.success("Berhasil");load();}catch(e){toast.error(apiError(e.response?.data?.detail));}};
  const approvedForEmail=["Approved","Partially Received","Fully Received"].includes(doc?.status);
  const sendEmail=async()=>{if(!approvedForEmail)return;const primary=(selectedSupplier?.contacts||[]).find(x=>x.is_primary)||(selectedSupplier?.contacts||[])[0]||{};const initial=selectedSupplier?.email||primary.email||"";const to=window.prompt("Email tujuan supplier",initial);if(!to)return;const subject=window.prompt("Subject email",`Purchase Order ${doc?.no||""}`);if(subject===null)return;const message=window.prompt("Pesan email","Terlampir informasi Purchase Order yang telah disetujui.");if(message===null)return;try{await api.post(`/po/${id}/email`,{to,subject,message});toast.success(`PO berhasil dikirim ke ${to}`);load();}catch(e){toast.error(apiError(e.response?.data?.detail));}};
  const draft=!doc||doc.status==="Draft",waiting=doc?.status==="Waiting Approval",editable=isNew||editing,factor=l=>Number(l.conversion_factor)||1,ownQty=l=>num(l.display_qty??((Number(l.qty)||0)/factor(l))),convQty=(l,v)=>num((Number(v)||0)/factor(l)),unitText=l=>l.display_unit||l.unit||"",priceText=l=>rupiah(l.display_price??((Number(l.price)||0)*factor(l)));
  const defaults={warehouse_id:h.default_warehouse_id,project_id:h.default_project_id,unit_id:h.default_unit_id};
  const approvals=doc&&<div className="space-y-2">{(doc.approvals||[]).length===0&&<p className="text-sm text-muted-foreground">Belum ada workflow approval. Submit PO untuk membuat.</p>}{(doc.approvals||[]).map(a=><div key={a.id} className="flex items-center gap-3 rounded-md border p-3"><span className="h-7 w-7 rounded-full bg-muted flex items-center justify-center text-xs font-semibold">{a.seq}</span><div className="flex-1"><div className="text-sm font-medium">{a.approver_name||a.approver_email||a.role||`Level ${a.seq}`}</div><div className="text-xs text-muted-foreground">{a.approver_email||""}</div>{a.acted_by&&<div className="text-xs text-muted-foreground">{a.acted_by} · {fmtDateTime(a.acted_at)} {a.note?`· ${a.note}`:""}</div>}</div><StatusBadge status={a.status}/></div>)}</div>;
  const refs=doc&&<table className="w-full text-sm"><thead><tr className="text-left text-xs uppercase text-muted-foreground"><th className="p-2">Barang</th><th className="p-2">RO / MRO</th><th className="p-2 text-right">Qty</th><th className="p-2 text-right">Diterima</th></tr></thead><tbody>{doc.lines.map((l,i)=><tr key={i} className="border-t"><td className="p-2">{l.item_code}</td><td className="p-2 font-mono text-xs">{(l.ro_refs||[]).map(m=>`${m.ro_no}${m.mro_no?"/"+m.mro_no:""}`).join(", ")}</td><td className="p-2 text-right">{ownQty(l)} {unitText(l)}</td><td className="p-2 text-right">{convQty(l,l.received)}</td></tr>)}</tbody></table>;
  return <div><PageHeader title={isNew?"PO Baru":doc?.no} subtitle={doc&&<StatusBadge status={doc.status}/>}><Button variant="outline" onClick={()=>nav("/po")}><ArrowLeft className="h-4 w-4 mr-2"/>Kembali</Button>{isNew&&<Button variant={pull?"secondary":"outline"} onClick={()=>setPull(!pull)}><Download className="h-4 w-4 mr-2"/>{pull?"Tutup Sumber":"Tarik RO"}</Button>}{!isNew&&!editing&&<TransactionMutationActions module="po" id={id} onEdit={beginEdit} onDeleted={()=>nav("/po")}/>} {editing&&<Button variant="outline" onClick={load}><X className="h-4 w-4 mr-2"/>Batal Edit</Button>}{(isNew&&can("create")||editing&&can("edit"))&&<Button onClick={save}><Save className="h-4 w-4 mr-2"/>{editing?"Simpan Perubahan":"Simpan"}</Button>}{!isNew&&draft&&!editing&&can("submit")&&<Button onClick={()=>act("submit")}><Send className="h-4 w-4 mr-2"/>Submit Approval</Button>}{!isNew&&waiting&&!editing&&can("approve")&&<Button onClick={()=>act("approve")}><Check className="h-4 w-4 mr-2"/>Approve</Button>}{!isNew&&waiting&&!editing&&can("reject")&&<Button variant="outline" onClick={()=>act("reject",{reason:"Ditolak"})}><X className="h-4 w-4 mr-2"/>Reject</Button>}{!isNew&&doc&&!doc.cancelled&&!editing&&can("cancel")&&<Button variant="outline" onClick={()=>act("cancel",{})}><Ban className="h-4 w-4 mr-2"/>Batalkan</Button>}{!isNew&&!editing&&<Button variant="outline" onClick={()=>printDoc("PO",doc,{title:"PURCHASE ORDER",showPrice:canPrice})}><Printer className="h-4 w-4 mr-2"/>Print</Button>}{!isNew&&!editing&&approvedForEmail&&can("print")&&<Button onClick={sendEmail}><Mail className="h-4 w-4 mr-2"/>Kirim Email</Button>}</PageHeader>
    <TransactionProgress className="mb-4" stages={["Draft","Waiting Approval","Approved","Partially Received","Fully Received"]} status={isNew?"Draft":editing?"Edit":doc?.status}/><PullDialog open={pull} onClose={()=>setPull(false)} url="/pull/ro-for-po" title="Tarik RO — Pilih Item untuk PO" onConfirm={onPull} columns={[{key:"ro_no",label:"RO",mono:true},{key:"mro_no",label:"MRO",mono:true},{key:"item_code",label:"Kode",mono:true},{key:"item_name",label:"Barang"},{key:"unit",label:"Satuan"},{key:"qty_ro",label:"Qty RO",num:true},{key:"ordered",label:"Sudah PO",num:true},{key:"outstanding",label:"Sisa",num:true}]}/>
    <DocMetaTabs entity="po" entityId={id} references={<div className="space-y-6"><div><h3 className="font-semibold mb-2 font-head">Approval</h3>{approvals}</div><div><h3 className="font-semibold mb-2 font-head">Sumber Dokumen</h3>{refs}</div></div>}><div className="space-y-4"><Card><CardContent className="pt-6 space-y-6"><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4"><Field label="Tanggal"><DatePicker value={h.date} onChange={v=>setH({...h,date:v})} disabled={!editable}/></Field><Field label="Supplier"><Combobox options={masters.opts("suppliers",d=>d.name)} value={h.supplier_id} onChange={changeSupplier} disabled={!editable}/></Field><Field label="Buyer Contact"><Combobox options={buyerOptions} value={h.buyer_contact_id||""} onChange={v=>setH({...h,buyer_contact_id:v})} placeholder="Pilih karyawan / buyer" disabled={!editable}/></Field><Field label="Divisi"><Combobox options={masters.opts("divisions",d=>d.name)} value={h.division_id} onChange={v=>setH({...h,division_id:v})} disabled={!editable}/></Field><Field label="Termin Pembayaran"><Input value={h.payment_term||""} onChange={e=>setH({...h,payment_term:e.target.value})} disabled={!editable}/></Field><Field label="Delivery Term"><Input value={h.delivery_term||""} onChange={e=>setH({...h,delivery_term:e.target.value})} disabled={!editable} placeholder="Mengikuti default supplier, bisa disesuaikan"/></Field><Field label="Mata Uang"><Input value={h.currency||"IDR"} onChange={e=>setH({...h,currency:e.target.value})} disabled={!editable}/></Field><Field label="Estimasi Datang"><DatePicker value={h.eta} onChange={v=>setH({...h,eta:v})} disabled={!editable}/></Field><Field label="Gudang Default"><Combobox options={masters.opts("warehouses",d=>d.name)} value={h.default_warehouse_id} onChange={v=>setH({...h,default_warehouse_id:v})} disabled={!editable}/></Field><Field label="Rekening Supplier"><Combobox options={bankOptions} value={h.supplier_bank_id||""} onChange={v=>setH({...h,supplier_bank_id:v})} placeholder={selectedSupplier?"Pilih rekening":"Pilih supplier dulu"} disabled={!editable||!selectedSupplier||bankOptions.length===0}/></Field><DocumentHeaderDefaults h={h} setH={setH} masters={masters} readOnly={!editable} showTaxMode/><Field label="Supplier Reff"><Input value={h.supplier_ref||""} onChange={e=>setH({...h,supplier_ref:e.target.value})} disabled={!editable} placeholder="Contoh: Penawaran by WA / No. Quotation"/></Field><Field label="Internal Notes"><Input value={h.internal_notes||""} onChange={e=>setH({...h,internal_notes:e.target.value})} disabled={!editable}/></Field></div>
      {editable?<ItemLines lines={lines} onChange={handleLinesChange} masters={masters} fields={{warehouse:true,project:true,unit:true,notes:true}} showPrice={canPrice} defaults={defaults} taxInclusive={!!h.tax_inclusive}/>:<div className="border rounded-md overflow-x-auto"><table className="w-full text-sm zebra"><thead className="bg-muted"><tr className="text-left text-xs uppercase text-muted-foreground"><th className="p-2">Barang</th><th className="p-2 text-right">Qty</th><th className="p-2 text-right">Diterima</th>{canPrice&&<th className="p-2 text-right">Harga / Satuan</th>}{canPrice&&<th className="p-2">Pajak</th>}{canPrice&&<th className="p-2 text-right">Total</th>}</tr></thead><tbody>{lines.map((l,i)=><tr key={i} className="border-t"><td className="p-2">{l.item_code} — {l.item_name}</td><td className="p-2 text-right">{ownQty(l)} {unitText(l)}</td><td className="p-2 text-right">{convQty(l,l.received)}</td>{canPrice&&<td className="p-2 text-right">{priceText(l)}</td>}{canPrice&&<td className="p-2">{l.tax_name||`${num(l.tax)}%`}</td>}{canPrice&&<td className="p-2 text-right">{rupiah(l.total)}</td>}</tr>)}</tbody>{canPrice&&<tfoot><tr className="border-t bg-muted/50 font-semibold"><td colSpan={5} className="p-2 text-right">Grand Total</td><td className="p-2 text-right">{rupiah(doc?.grand_total)}</td></tr></tfoot>}</table></div>}</CardContent></Card><DocumentMessageEditor module="po" value={h.document_message} onChange={v=>setH({...h,document_message:v})} useDefault={isNew} readOnly={!editable}/></div></DocMetaTabs>
  </div>;
}
